# Configuration file for SuperSID Next - Montevideo Observatory (#281)

[observatory]
code = "#281"
location = "Montevideo, Uruguay"
operator = "Alejandro Arévalo"

[audio]
device = "default"
sample_rate = 48000
channels = 1
chunk_ms = 250

[processing]
window_seconds = 5
step_seconds = 1
sensitivity = 0.8

[[channels]]
name = "DHO38"
freq = 38300
bw = 40

[[channels]]
name = "GQD22"
freq = 22000
bw = 40
