# Global VLF Transmitters Catalog for SuperSID App

[[transmitters]]
name = "DHO38"
freq = 38300        # Hz
location = "Rhauderfehn, Germany"
country = "Germany"
power_kw = 800

[[transmitters]]
name = "GQD22"
freq = 22000
location = "Skelton, United Kingdom"
country = "UK"
power_kw = 400

[[transmitters]]
name = "NAA24"
freq = 24000
location = "Cutler, Maine"
country = "USA"
power_kw = 1000

[[transmitters]]
name = "NPM21"
freq = 21000
location = "Lualualei, Hawaii"
country = "USA"
power_kw = 424

[[transmitters]]
name = "NLK24"
freq = 24000
location = "Jim Creek, Washington"
country = "USA"
power_kw = 192

[[transmitters]]
name = "JJI22"
freq = 22000
location = "Ebino, Japan"
country = "Japan"
power_kw = 400
