# Global catalog of VLF transmitters

[[transmitters]]
name = "DHO38"
freq = 38300
bw = 40
location = "Germany"

[[transmitters]]
name = "GQD22"
freq = 22000
bw = 40
location = "UK"

[[transmitters]]
name = "NAA24"
freq = 24000
bw = 40
location = "USA"

[[transmitters]]
name = "NWC19"
freq = 19900
bw = 40
location = "Australia"
